##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    - autoconf-archive
    - clang
    - gcc
    - git
    - make
    - startup-notification
    - which
    - pacman
    - gtk3
    - glib2
    - ayatana-ido
    - mate-common

  debian:
    # Useful URL: https://salsa.debian.org/debian-ayatana-team/libayatana-indicator
    - autopoint
    - clang
    - clang-tools
    - cppcheck
    - git
    - at-spi2-core
    - libtool
    - intltool
    - mate-common
    - gtk-doc-tools
    - libglib2.0-dev
    - libgtk2.0-dev
    - libgtk-3-dev
    - libayatana-ido3-dev
    - systemd
    - dbus-test-runner
    - xauth
    - xvfb

  ubuntu:
    - autopoint
    - clang
    - clang-tools
    - git
    - at-spi2-core
    - libtool
    - intltool
    - mate-common
    - gtk-doc-tools
    - libglib2.0-dev
    - libgtk2.0-dev
    - libgtk-3-dev
    - libayatana-ido3-dev
    - systemd

variables:
  - 'CHECKERS="
    -enable-checker deadcode.DeadStores
    -enable-checker alpha.deadcode.UnreachableCode
    -enable-checker alpha.core.CastSize
    -enable-checker alpha.core.CastToStruct
    -enable-checker alpha.core.IdenticalExpr
    -enable-checker alpha.core.SizeofPtr
    -enable-checker alpha.security.ArrayBoundV2
    -enable-checker alpha.security.MallocOverflow
    -enable-checker alpha.security.ReturnPtrRange
    -enable-checker alpha.unix.SimpleStream
    -enable-checker alpha.unix.cstring.BufferOverlap
    -enable-checker alpha.unix.cstring.NotNullTerminated
    -enable-checker alpha.unix.cstring.OutOfBounds
    -enable-checker alpha.core.FixedAddr
    -enable-checker security.insecureAPI.strcpy"'

build_scripts:
  - if [ ${DISTRO_NAME} == "debian" ];then
  -     export CFLAGS+=" -Wsign-compare -Wunused-parameter"
  -     cppcheck --enable=warning,style,performance,portability,information,missingInclude .
  - fi

  - NOCONFIGURE=1 ./autogen.sh
  - scan-build $CHECKERS ./configure --prefix=/usr --enable-gtk-doc --enable-compile-warnings=maximum --enable-tests
  - if [ $CPU_COUNT -gt 1 ]; then
  -     if [ ${DISTRO_NAME} == "debian" ];then
  -         scan-build $CHECKERS --keep-cc --use-cc=clang --use-c++=clang++ -o html-report make -j $CPU_COUNT
  -         make clean
  -     fi
  -     scan-build $CHECKERS --keep-cc -o html-report make -j $CPU_COUNT
  - else
  -     if [ ${DISTRO_NAME} == "debian" ];then
  -         scan-build $CHECKERS --keep-cc --use-cc=clang --use-c++=clang++ -o html-report make
  -         make clean
  -     fi
  -     scan-build $CHECKERS --keep-cc -o html-report make
  - fi

after_scripts:
  - if [ ${BUILD_TYPE} == "scripts" ];then
  -     if [ ${DISTRO_NAME} == "debian" ];then
  -         make check
  -         cat tests/test-suite.log
  -     fi
  - fi
